import {esc,icon} from '../ui.js';
const keys=['workMode','floor','field','refYear','refMonth','assignee','expType','expSubType','cost','workVendor','workContact','workRole','workPhone','workMemo','estimateMemo','material','qty'];
const fields=[{key:'floor',label:'층 / 호실'},{key:'field',label:'업무 분야'},{key:'assignee',label:'담당자'},{key:'cost',label:'비용 (원)',type:'number'}];
function renderEditor(host,draft,record={}){
 for(const key of keys)if(draft[key]===undefined&&record[key]!==undefined)draft[key]=record[key];
 draft.workMode??=record.workMode||((draft.workVendor||Number(draft.cost))?'full':'simple');
 const field=(key,label,type='text',extra='')=>`<label class="field"><span>${label}</span><input data-detail="${key}" type="${type}" maxlength="2000" ${type==='number'?'min="0"':''} ${extra} value="${esc(draft[key]??'')}"></label>`;
 const select=(key,label,options)=>`<label class="field"><span>${label}</span><select data-detail="${key}">${options.map(([v,l])=>`<option value="${v}" ${String(draft[key]??'')===String(v)?'selected':''}>${l}</option>`).join('')}</select></label>`;
 const memo=(key,label)=>`<label class="field full"><span>${label}</span><textarea data-detail="${key}" maxlength="2000">${esc(draft[key]??'')}</textarea></label>`;
 host.innerHTML=`<section class="worklog-editor"><div class="extra-label">${icon('building')} 업무일지 상세 <a href="../worklog.html" target="_blank" rel="noopener">업무일지 열기 ↗</a></div><div class="work-tabs" aria-label="업무 종류"><button type="button" data-work-mode="simple">일반업무</button><button type="button" data-work-mode="full">외주·비용</button></div><input type="hidden" data-detail="workMode" value="${draft.workMode==='full'?'full':'simple'}"><div class="form-grid">${field('floor','층 / 호실','text','list="work-floors" placeholder="층 선택 또는 입력"')}${field('field','분야','text','placeholder="전기 · 시설 · 청소"')}${field('refYear','대상년도','number','step="1" placeholder="2026"')}${select('refMonth','대상월',[['','선택 안 함'],...Array.from({length:12},(_,i)=>[i+1,(i+1)+'월'])])}${field('assignee','담당자')}</div><datalist id="work-floors">${['옥탑층',...Array.from({length:20},(_,i)=>(20-i)+'층'),...Array.from({length:6},(_,i)=>'지하'+(i+1)+'층')].map(x=>`<option value="${x}">`).join('')}</datalist><div class="work-cost-panel"><div class="form-grid">${select('expType','지출종류',[['없음','없음'],['개인비용','개인지출 (선결재)'],['전표','선납부 (전표 · 월별청구)'],['후불청구','기타정산 (세금계산서)']])}${field('cost','금액 (원)','number','step="1"')}${field('expSubType','하위 구분')}${field('workVendor','담당업체')}${field('workContact','업체 담당자')}${field('workRole','직책')}${field('workPhone','전화번호','tel')}${memo('workMemo','업체 메모')}${memo('estimateMemo','견적 메모')}</div></div><details class="work-materials"><summary>자재 사용 내역</summary><div class="form-grid">${field('material','자재명')}${field('qty','수량','number','step="any"')}</div>${Array.isArray(record.materials)&&record.materials.length?`<p class="form-note">원본 자재 ${record.materials.length}건은 유지됩니다. 재고 출고와 다중 자재 변경은 업무일지에서 처리해 주세요.</p>`:''}</details><p class="form-note worklog-scope">업무일지와 같은 항목으로 기록합니다. 기존 업무일지와의 자동 동기화·업체 검색·재고 출고·파일 첨부는 아직 연결 전입니다.${record.photos?.length||record.attachments?.length?' 기존 사진과 첨부 정보는 유지됩니다.':''}</p></section>`;
 const mode=next=>{draft.workMode=next;host.querySelector('[data-detail=workMode]').value=next;host.querySelector('.work-cost-panel').hidden=next!=='full';host.querySelectorAll('[data-work-mode]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.workMode===next));};
 host.querySelectorAll('[data-work-mode]').forEach(b=>b.onclick=()=>mode(b.dataset.workMode));mode(draft.workMode);
}
export default {id:'worklog',label:'워크로그',description:'업무일지의 일반업무·외주 비용 항목을 캘린더에 기록합니다.',icon:'building',color:'#5373cf',fields,renderEditor};
