import test from 'node:test';import assert from 'node:assert/strict';import {notificationRoutes,deliveryState} from '../server/notifications.mjs';
// Transport and persistence are isolated so failure states can be verified without sending notifications.
function database(){const data=new Map();const ref=path=>({id:path.split('/').at(-1),firestore:db,collection:n=>col(path+'/'+n),get:async()=>snap(path),set:async(v,{merge}={})=>data.set(path,merge?{...data.get(path),...v}:v),delete:async()=>data.delete(path)});const snap=path=>({exists:data.has(path),data:()=>structuredClone(data.get(path)),id:path.split('/').at(-1),ref:ref(path)});const col=path=>({doc:id=>ref(path+'/'+id),orderBy:()=>col(path),limit:()=>col(path),get:async()=>{const docs=[...data.keys()].filter(k=>k.startsWith(path+'/')&&!k.slice(path.length+1).includes('/')).map(snap);return {docs,empty:!docs.length};}});const db={runTransaction:async fn=>fn({get:r=>r.get(),set:(r,v,o)=>r.set(v,o)})};return {root:ref('spaces/family'),data};}
async function call(root,route,body,webpush,uid='a'){let result;const found=await notificationRoutes({root,uid,role:'editor',route,req:{method:body?'POST':'GET',body},res:{json:x=>result=x},webpush,vapid:()=>['mailto:test@example.com','public','private']});assert.equal(found,true);return result;}
test('transport acceptance is not receipt confirmation',()=>{assert.equal(deliveryState({accepted:1,failed:0}),'accepted');assert.equal(deliveryState({accepted:1,failed:1}),'partial');assert.equal(deliveryState({accepted:0,failed:1}),'failed');assert.equal(deliveryState({accepted:0,failed:0}),'no-device');});
test('test push is idempotent and rate limited',async()=>{const {root}=database();await root.collection('members').doc('a').collection('subscriptions').doc('s').set({subscription:{endpoint:'test'}});let count=0;const transport={setVapidDetails(){},async sendNotification(){count++;}};const a=await call(root,'/notifications/test',{requestId:'request-one'},transport);await call(root,'/notifications/test',{requestId:'request-one'},transport);assert.equal(count,1);assert.equal(a.state,'accepted');assert.equal(a.openedAt,undefined);await assert.rejects(call(root,'/notifications/test',{requestId:'request-two'},transport),e=>e.status===429);});
test('expired device is not reported as sent',async()=>{const {root}=database();await root.collection('members').doc('a').collection('subscriptions').doc('s').set({subscription:{}});const transport={setVapidDetails(){},async sendNotification(){throw Object.assign(Error('expired'),{statusCode:410});}};const result=await call(root,'/notifications/test',{requestId:'request-one'},transport);assert.equal(result.state,'no-device');assert.equal((await call(root,'/subscriptions')).devices.length,0);});
test('notification list rechecks current event privacy',async()=>{const {root}=database();await root.collection('events').doc('private').set({ownerId:'b',visibility:'personal'});await root.collection('members').doc('a').collection('notifications').doc('notice').set({eventId:'private',title:'private content',createdAt:1});assert.equal((await call(root,'/notifications')).notifications.length,0);await assert.rejects(call(root,'/notifications/opened',{id:'notice'}),e=>e.status===403);});
test('opening notification is scoped to its recipient and idempotent',async()=>{const {root}=database();await root.collection('members').doc('a').collection('notifications').doc('test-id').set({kind:'test',state:'accepted'});await assert.rejects(call(root,'/notifications/opened',{id:'test-id'},null,'b'),e=>e.status===404);const a=await call(root,'/notifications/opened',{id:'test-id'}),b=await call(root,'/notifications/opened',{id:'test-id'});assert.equal(a.openedAt,b.openedAt);});
